### ISSUE TITLE
Debian 13 support 

### ISSUE THREAD

**Issue by padamatavijji** [flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver#12]
Embedded mongo db is not working with linux debian 13 version. Could you please address this
Version and Platform info
GenericFeatureAwareVersion{8.0.0-rc9}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Debian, version=DEBIAN_13}

**Comment by michaelmosmann** [comment]
@padamatavijji still an issue? please reopen if needed.
