### ISSUE TITLE
wrong link for mongo 6.0.4 version on ubuntu 20.04

### ISSUE THREAD

**Issue by linuxidefix** [flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver#6]
# Description
A wrong mongodb archive is downloaded with Ubuntu 20.04 + mongo 6.0.4
(https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.4.tgz)
( causing ssl issue: "error while loading shared libraries: libcrypto.so.3" as ubuntu20.04 runs openssl v1 not v3)

# Expectation
I expect https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-6.0.4.tgz to be downloaded instead

# PR 
Complete description on the bug and fix on:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/pull/5#issue-1581604175

**Comment by michaelmosmann** [comment]
@linuxidefix thanks:) .. new release will be in maven central in 12-24hrs
