### ISSUE TITLE
Debian 12 Support

### ISSUE THREAD

**Issue by d3v3lop3rDE** [flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver#7]
Hi,

I have problem getting embedded mongo to work with Debian 12. I've tried various combinations of versions, like 7.0.0, 7.0.0-rc10. Target version would be 5.0.21 though. 

Iam running Debian 12 with Linux debian 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
and
`<dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo.spring27x</artifactId>
            <version>4.9.3</version>
        </dependency>`

Here is part of the exception:

`could not resolve package for GenericFeatureAwareVersion{7.0.0}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Debian}
--------------
(os=Windows)
  (os=Windows and bitSize=B64) and (3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-x86_64-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9)
    url=/windows/mongodb-windows-x86_64-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3)
    url=/win32/mongodb-win32-x86_64-2012plus-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
    url=/win32/mongodb-win32-x86_64-2008plus-ssl-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-x86_64-2008plus-{version}.zip (ZIP)
  (os=Windows and bitSize=B64) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/win32/mongodb-win32-x86_64-{version}.zip (ZIP)
  (os=Windows and bitSize=B32) and (3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-i386-{version}.zip (ZIP)
  (os=Windows and bitSize=B32) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/win32/mongodb-win32-i386-{version}.zip (ZIP)
  (os=Windows)
    fail
(os=OS_X)
  (os=OS_X and bitSize=B64 and cpuType=ARM) and (6.0.1-6.0.3)
    url=/osx/mongodb-macos-arm64-{version}.tgz (TGZ)
  (os=OS_X and bitSize=B64) and (4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.4-3.0.15)
    url=/osx/mongodb-osx-ssl-x86_64-{version}.tgz (TGZ)
  (os=OS_X and bitSize=B64) and (3.5.5-3.5.5 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.3.1-3.3.1 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/osx/mongodb-osx-x86_64-{version}.tgz (TGZ)
  (os=OS_X and bitSize=B64) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3)
    url=/osx/mongodb-macos-x86_64-{version}.tgz (TGZ)
  (os=OS_X)
    fail
(os=Linux)
  (os=Linux and (version is any of Ubuntu_16_04, Ubuntu_16_10, Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9)
      url=/linux/mongodb-linux-aarch64-ubuntu2004-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9)
      url=/linux/mongodb-linux-x86_64-ubuntu2004-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3)
      url=/linux/mongodb-linux-aarch64-ubuntu1804-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.1-4.0.28 or 3.6.20-3.6.23)
      url=/linux/mongodb-linux-x86_64-ubuntu1804-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_16_04, Ubuntu_16_10)) and (4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7)
      url=/linux/mongodb-linux-arm64-ubuntu1604-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_16_04, Ubuntu_16_10)) and (4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.7-3.2.22)
      url=/linux/mongodb-linux-x86_64-ubuntu1604-{version}.tgz (TGZ)
  (os=Linux and (version is any of LINUX_MINT_19_0, LINUX_MINT_19_1, LINUX_MINT_19_2, LINUX_MINT_19_3, LINUX_MINT_20_0, LINUX_MINT_20_1, LINUX_MINT_20_2, LINUX_MINT_20_3, LINUX_MINT_21_0))
    use Ubuntu_18_04 for LINUX_MINT_19_0, LINUX_MINT_19_1, LINUX_MINT_19_2, LINUX_MINT_19_3 and Ubuntu_20_04 for LINUX_MINT_20_0, LINUX_MINT_20_1, LINUX_MINT_20_2, LINUX_MINT_20_3 and Ubuntu_22_04 for LINUX_MINT_21_0
  (os=Linux and (version is any of DEBIAN_11, DEBIAN_10, DEBIAN_9))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_11)) and (6.0.1-6.0.3 or 5.0.12-5.0.14)
      url=/linux/mongodb-linux-x86_64-debian11-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_10, DEBIAN_11)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.1-4.2.3)
      url=/linux/mongodb-linux-x86_64-debian10-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_9)) and (5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.5-3.6.23)
      url=/linux/mongodb-linux-x86_64-debian92-{version}.tgz (TGZ)
  (os=Linux and (version is any of CentOS_6, CentOS_7, CentOS_8, CentOS_9, Redhat_6, Redhat_7, Redhat_8, Redhat_9, Oracle_6, Oracle_7, Oracle_8, Oracle_9))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_6, Redhat_6, Oracle_6)) and (4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-rhel62-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_7, Redhat_7, Oracle_7)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-rhel70-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.1-4.2.3 or 4.0.14-4.0.28 or 3.6.17-3.6.23 or 3.4.24-3.4.24)
      url=/linux/mongodb-linux-x86_64-rhel80-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.4-4.4.9)
      url=/linux/mongodb-linux-aarch64-rhel82-{version}.tgz (TGZ)
  (os=Linux and (version is any of AmazonLinux, AmazonLinux2))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of AmazonLinux2)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.4-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.13-4.2.16)
      url=/linux/mongodb-linux-aarch64-amazon2-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of AmazonLinux2)) and (6.0.1-6.0.3 or 5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.18-4.2.19 or 4.2.22-4.2.23 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.22-3.6.23)
      url=/linux/mongodb-linux-x86_64-amazon2-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of AmazonLinux)) and (5.0.12-5.0.14 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.18 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9 or 4.2.22-4.2.23 or 4.2.18-4.2.19 or 4.2.5-4.2.16 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-amazon-{version}.tgz (TGZ)
  (os=Linux and bitSize=B64) and (4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/linux/mongodb-linux-x86_64-{version}.tgz (TGZ)
  (os=Linux and bitSize=B32) and (3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/linux/mongodb-linux-i686-{version}.tgz (TGZ)
  (os=Linux and bitSize=B64) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/linux/mongodb-linux-x86_64-{version}.tgz (TGZ)
  (os=Linux and bitSize=B32) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/linux/mongodb-linux-i686-{version}.tgz (TGZ)
  (os=Linux)
    fallback to Ubuntu_20_04
(os=Solaris)
  (os=Solaris and bitSize=B64) and (3.4.0-3.4.5 or 3.2.0-3.2.14 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/sunos5/mongodb-sunos5-x86_64-{version}.tgz (TGZ)
  (os=Solaris and bitSize=B64) and (3.3.1-3.3.1 or 3.5.5-3.5.5)
    url=/sunos5/mongodb-sunos5-x86_64-{version}.tgz (TGZ)
  (os=Solaris)
`

Best regards

**Comment by michaelmosmann** [comment]
@d3v3lop3rDE i have to add debian12 into the mix...

**Comment by ajdergute** [comment]
As of today there is `DebianUsesUbuntuPackageFinder`,  but it's not listed in `LinuxPackageFinder`.

At least in my environment Debian 12 still revolves packages from Debian 11, which fails because only OpenSSL 3.x is available.

**Comment by michaelmosmann** [comment]
@ajdergute .. ah.. yes.. ok.. sorry.. hahaha.. what a bug. Will fix this soon.

**Comment by michaelmosmann** [comment]
@ajdergute .. new release (4.10.1) should be in maven central in some hours.

**Comment by ajdergute** [comment]
That's a very awesome response time. Thanks a lot.

**Comment by michaelmosmann** [comment]
@ajdergute I am not always that fast.. :)
