### ISSUE TITLE
Alma Support

### ISSUE THREAD

**Issue by laurentschoelens** [flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver#9]
Alma Linux is not detected and fallback to Ubuntu which fails
If overriding as Centos, everything works.
Please could you add support for Alma detection

Example of `/etc/centos-release` file in Alma context :
```
AlmaLinux release 8.8 (Sapphire Caracal)
```

**Comment by laurentschoelens** [comment]
PR created again 😉 https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/pull/10
Hope the snapshot part won't break anything

**Comment by laurentschoelens** [comment]
@michaelmosmann any news on this ? Thanks

**Comment by michaelmosmann** [comment]
@laurentschoelens .. i was on vacation.. so i will make an release today or maybe tomorrow..

**Comment by laurentschoelens** [comment]
Nice, thanks!

**Comment by michaelmosmann** [comment]
@laurentschoelens .. released 4.12.3, should be in maven central in some hours..
i will close this issue, reopen if needed

**Comment by laurentschoelens** [comment]
Tested `4.12.3` version by removing also the "hack" property introduced : it worked 😄 
Many thanks for the fast and quick release 👍
